desempProjectFinal/brazalete_datos/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'brazalete_datos'

urlpatterns = [
    path('', views.index, name="index"),
    path('about/', views.about_us, name='about_us'),
    path('help/', views.help, name='help'),
    path('reminders/', views.fetch_reminders, name='fetch_reminders'),  # Actualizamos la ruta
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

desempProjectFinal/desempProjectFinal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from allauth.account.decorators import secure_admin_login

admin.autodiscover()
admin.site.login = secure_admin_login(admin.site.login)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('brazalete_datos.urls')),
    path('accounts/', include('allauth.urls')),  # Incluir las URLs de Allauth
    path("i18n/", include("django.conf.urls.i18n")),
    path("accounts/profile/", TemplateView.as_view(template_name="profile.html")),
]

desempProjectFinal/brazalete_datos/models.py
from django.db import models

# Create your models here.

desempProjectFinal/brazalete_datos/views.py
from django.shortcuts import render
from .firebase import db
from datetime import datetime
from django.contrib.auth.decorators import login_required

def index(request):
    return render(request, 'index.html')

def about_us(request):
    return render(request, 'about_us.html')

def help(request):
    return render(request, 'help.html')

@login_required
def fetch_reminders(request):
    ref_reminders = db.reference('/reminders')
    reminders = ref_reminders.get()

    ref_closest_reminder = db.reference('/closestReminders')
    closest_reminder = ref_closest_reminder.get()

    # Formatear la fecha
    if closest_reminder:
        reminder_time = closest_reminder.get('reminderTime')
        if reminder_time:
            # Convertir el timestamp a una fecha legible
            closest_reminder['reminderTime'] = datetime.fromtimestamp(reminder_time / 1000).strftime('%d/%m/%Y %H:%M:%S')

    for d, valor in reminders.items():
        if valor:
            reminder_time = valor["reminderTime"]
        if reminder_time:
            valor['reminderTime'] = datetime.fromtimestamp(reminder_time / 1000).strftime('%d/%m/%Y %H:%M:%S')
    context = {
        'reminders': reminders,
        'closest_reminder': closest_reminder
    }
    return render(request, 'closest_reminders.html', context)

desempProjectFinal/brazalete_datos/templates/429.html
{% extends "allauth/layouts/entrance.html" %}
{% load allauth %}
{% block head_title %}
    Too Many Requests
{% endblock head_title %}
{% block content %}
    {% element h1 %}
        Too Many Requests
    {% endelement %}
    <p>You are sending too many requests.</p>
{% endblock content %}

desempProjectFinal/brazalete_datos/templates/about_us.html
{% extends "layout.html" %}
{% load static %}
{% block content %}
    <div class="jumbotron text-center animate__animated animate__fadeIn">
        <h1 class="display-4">Sobre Nosotros</h1>
        <p class="lead">Conoce más sobre Pulse Care y cómo ayudamos a recordar la toma de medicamentos.</p>
    </div>

    <div class="container main-content animate__animated animate__fadeIn">
        <div class="row">
            <div class="col-md-6">
                <p class="text-justify">
                    Pulse Care es un proyecto innovador diseñado para ayudar a las personas a recordar cuándo deben tomar sus medicamentos. 
                    Nuestro brazalete inteligente emite recordatorios mediante vibraciones, luces RGB y alarmas sonoras para asegurar que 
                    nunca olvides tomar tus pastillas a tiempo. También cuenta con botones para confirmar la toma de medicamentos y para emergencias.
                </p>
                <p class="text-justify">
                    Además, Pulse Care se conecta a una aplicación móvil que permite a los usuarios y sus cuidadores gestionar las alertas de medicamentos, 
                    revisar el historial de tomas y recibir notificaciones en caso de emergencia. La app está disponible tanto para Android como para iOS.
                </p>
            </div>
            <div class="col-md-6">
                <img src="{% static 'images/brazalete..jpg' %}" alt="Pulsercar Image" class="about-image">
            </div>
        </div>
    </div>
{% endblock %}

desempProjectFinal/brazalete_datos/templates/closest_reminders.html
{% extends "layout.html" %}
{% load static %}
{% block content %}
  <div class="container-fluid full-height-section">
    <h2>Todos los recordatorios</h2>
    <div class="container">
      <table class="table animate__animated animate__fadeIn">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Id</th>
            <th scope="col">Medecine name</th>
            <th scope="col">Reminder Time</th>
            <th scope="col">Description</th>
          </tr>
        </thead>
        <tbody>
          {% if reminders %}
            {% for key, value in reminders.items %}
              <tr>
                <th scope="row">{{ key }}</th>
                <td>{{ value.medicineName }}</td>
                <td>{{ value.reminderTime }}</td>
                <td>{{ value.description }}</td>
              </tr>
            {% endfor%}
          {% else %}
            <tr>
              <td colspan="4">No data available</p>
            </tr>
          {% endif %}
      </table>
    </div>

    <hr class="hr-custom">


    <div class="card card-esp animate__animated animate__fadeIn">
        <div class="card-header card-header-esp">
            Recordatorio más cercano
        </div>
        <div class="card-body card-body-esp">
            {% if closest_reminder %}
                <p class="card-text"><strong>ID:</strong> {{ closest_reminder.id }}</p>
                <p class="card-text"><strong>Medicine Name:</strong> {{ closest_reminder.medicineName }}</p>
                <p class="card-text"><strong>Reminder Time:</strong> {{ closest_reminder.reminderTime }}</p>
                <p class="card-text"><strong>State:</strong> {{ closest_reminder.state }}</p>
            {% else %}
                <p class="card-text">No data available</p>
            {% endif %}
        </div>
        <div class="card-footer">
            &copy; PulseCare 2024
        </div>
    </div>
  </div>
  <script>
    gsap.from(".card", {duration: 1, y: 50, opacity: 0, stagger: 0.3});
  </script>
{% endblock %}

desempProjectFinal/brazalete_datos/templates/help.html
{% extends "layout.html" %}
{% load static %}
{% block content %}
    <div class="jumbotron text-center animate__animated animate__fadeIn">
        <h1 class="display-4">Ayuda</h1>
        <p class="lead">Encuentra respuestas a las preguntas más frecuentes sobre Pulsercar.</p>
    </div>
    <div class="container main-content animate__animated animate__fadeIn">
        <div class="row">
            <div class="col-md-6">
                <p class="text-justify">
                    Si necesitas ayuda con tu Pulse Care, aquí encontrarás las respuestas a las preguntas más frecuentes. 
                    Si tienes algún problema o necesitas asistencia adicional, no dudes en contactarnos.
                </p>
                <div class="accordion" id="faqAccordion">
                    <div class="card card-esp">
                        <div class="card-header card-header-esp" id="headingOne">
                            <h2 class="mb-0">
                                <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                    ¿Cómo configuro mi Pulse Care?
                                </button>
                            </h2>
                        </div>
                        <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#faqAccordion">
                            <div class="card-body card-body-esp">
                                Para configurar tu Pulse Care, sigue los siguientes pasos: [Instrucciones detalladas]
                            </div>
                        </div>
                    </div>
                    <div class="card card-esp">
                        <div class="card-header card-header-esp" id="headingTwo">
                            <h2 class="mb-0">
                                <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                    ¿Qué hacer si mi Pulse Care no responde?
                                </button>
                            </h2>
                        </div>
                        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#faqAccordion">
                            <div class="card-body card-body-esp">
                                Si tu Pulse Care no responde, intenta las siguientes soluciones: [Soluciones detalladas]
                            </div>
                        </div>
                    </div>
                    <div class="card card-esp">
                        <div class="card-header card-header-esp" id="headingThree">
                            <h2 class="mb-0">
                                <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                    Contacta con el soporte técnico
                                </button>
                            </h2>
                        </div>
                        <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#faqAccordion">
                            <div class="card-body card-body-esp">
                                Para contactar con el soporte técnico, envía un correo a <a href="mailto:soporte@pulsercar.com">soporte@pulsercar.com</a>.
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <img src="{% static 'images/brazalet.jpg' %}" alt="Help Image" class="help-image">
            </div>
        </div>
    </div>
{% endblock %}

desempProjectFinal/brazalete_datos/templates/index.html
{% extends "layout.html" %}
{% load static %}
{% block content %}
<!--
<script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/three/examples/js/loaders/GLTFLoader.js"></script>
-->
<div id="carouselExampleIndicators" class="carousel slide animate__animated animate__backInDown">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static 'images/pulsera_carrusel.png' %}" class="img-carrusel color-carr" alt="...">
    </div>
    <div class="contenedor-z">
      <h3>Nuestro brazalete</h3>
        <p>Pulse Care Características Principales: Intuitiva, conectividad 
          y Monitoreo Remoto, Diseño Ergonómico y Elegante, 
          Batería de Larga Duración</p>
      <a class="btn-personal" href="{% url 'brazalete_datos:fetch_reminders' %}">Ver mis recordatorios</a>
    </div>
  </div>
</div>
<div class="container mt-3 animate__animated animate__backInDown">
  <div class="row">
    <div class="col-md-6">
      <h3>Sobre nosotros</h3>
      <img src="{% static 'images/sobre-nosotros-index.avif' %}" class="w-100">
    </div>
    <div class="col-md-6 justify-content-center align-content-center text-center mt-3">
      <p><strong>PulseCare</strong> es una empresa innovadora dedicada a mejorar la salud 
        y el bienestar de los adultos mayores a través de tecnología accesible 
        y fácil de usar. Nuestro producto estrella es una pulsera inteligente 
        diseñada específicamente para recordar a los usuarios cuándo deben 
        tomar sus medicamentos.</p>
      <a href="{% url 'brazalete_datos:about_us' %}" class="btn pers">Mas información</a>
    </div>
  </div>
</div>
<!-- Testimonials Section -->
<div class="container mt-3 animate__animated animate__backInDown">
  <div class="testimonials">
      <h2>Testimonios</h2>
      <div class="container">
        <div class="row">
          <div class="col-md-4 testimonial-item">
            <img src="{% static 'images/user-2.png' %}" alt="User 1" class="user">
            <h5>Juan Pérez</h5>
            <p>"PulseCare me ha ayudado a nunca olvidar mis medicamentos. ¡Es una maravilla!"</p>
          </div>
          <div class="col-md-4 testimonial-item">
            <img src="{% static 'images/user-2.png' %}" alt="User 2">
            <h5>María López</h5>
            <p>"La app es muy fácil de usar y el botón de emergencia me da mucha tranquilidad."</p>
          </div>
          <div class="col-md-4 testimonial-item">
            <img src="{% static 'images/user-2.png' %}" alt="User 3">
            <h5>Carlos Gómez</h5>
            <p>"Desde que uso PulseCare, mis cuidadores también están más tranquilos."</p>
          </div>
        </div>
      </div>
    </div>
</div>
<!--
<canvas id='myCanvas'></canvas>

<script src="{% static 'js/pulsera-cargado.js' %}"></script>
-->
<!-- Testimonials Section END -->

{% endblock %}

desempProjectFinal/brazalete_datos/templates/layout.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Pulse Care{% block title %} {% endblock %}</title>
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
  </head>
  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg fixed-top">
      <div class="container">
        <a class="navbar-brand" href="{% url 'brazalete_datos:index' %}">Pulse Care</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'brazalete_datos:index' %}">Inicio
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'brazalete_datos:fetch_reminders' %}">Recordatorios</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'brazalete_datos:about_us' %}">Acerca de</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'brazalete_datos:help' %}">Ayuda</a>
            </li>
          </ul>
          {% if user.is_authenticated %}
              {% url 'account_email' as email_url %}
              {% url 'socialaccount_connections' as socialaccount_url %}
              {% if email_url or socialaccount_url %}
                  <a href="{% if email_url %}{{ email_url }}{% else %}{{ socialaccount_url }}{% endif %}"
                     class="btn btn-man">{% translate "Manage Account" %}</a>
              {% endif %}
              <a href="{% url 'account_logout' %}" class="btn btn-logout">{% translate "Sign Out" %}</a>
          {% else %}
              <a href="{% url 'account_login' %}" class="btn btn-login">{% translate "Sign In" %}</a>
              {% url 'account_signup' as signup_url %}
              {% if signup_url %}
                  <a href="{{ signup_url }}" class="btn btn-reg">{% translate "Sign Up" %}</a>
              {% endif %}
          {% endif %}
        </div>
      </div>
    </nav>
    <!-- Navigation END -->

    <!-- Contenido de la pagina -->
    <section>
      {% block content %} {% endblock %}
    </section>
    <!-- Contenido de la pagina END -->

    <!-- Footer -->
    <footer class="py-5 footer-pers">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Pulse Care 2024</p>
      </div>
      <!-- /.container -->
    </footer>
    <!-- Bootstrap core JavaScript -->    
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.9.1/gsap.min.js"></script>
  </body>
</html>

desempProjectFinal/brazalete_datos/templates/mfa/base_manage.html
{% extends "allauth/layouts/manage.html" %}
{% block nav_class_mfa %}{{ block.super }} active{% endblock %}

desempProjectFinal/brazalete_datos/templates/profile.html
{% extends "allauth/layouts/manage.html" %}
{% load allauth %}
{% block content %}
    {% element h1 %}
        Profile
    {% endelement %}
    <p>Your profile</p>
{% endblock content %}

desempProjectFinal/brazalete_datos/templates/usersessions/base_manage.html
{% extends "allauth/layouts/manage.html" %}
{% block nav_class_usersessions %}{{ block.super }} active{% endblock %}